/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as MarufRouteImport } from './routes/maruf'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsLevelRouteImport } from './routes/levels.$level'
import { Route as LearnTopicRouteImport } from './routes/learn.$topic'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const MarufRoute = MarufRouteImport.update({
  id: '/maruf',
  path: '/maruf',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelRoute = LevelsLevelRouteImport.update({
  id: '/levels/$level',
  path: '/levels/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicRoute = LearnTopicRouteImport.update({
  id: '/learn/$topic',
  path: '/learn/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/credits': typeof CreditsRoute
  '/daily': typeof DailyRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/glossary': typeof GlossaryRoute
  '/maruf': typeof MarufRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/levels/$level': typeof LevelsLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/credits': typeof CreditsRoute
  '/daily': typeof DailyRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/glossary': typeof GlossaryRoute
  '/maruf': typeof MarufRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/levels/$level': typeof LevelsLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/credits': typeof CreditsRoute
  '/daily': typeof DailyRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/glossary': typeof GlossaryRoute
  '/maruf': typeof MarufRoute
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/levels/$level': typeof LevelsLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/categories'
    | '/credits'
    | '/daily'
    | '/faq'
    | '/favorites'
    | '/glossary'
    | '/maruf'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/learn/$topic'
    | '/levels/$level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/categories'
    | '/credits'
    | '/daily'
    | '/faq'
    | '/favorites'
    | '/glossary'
    | '/maruf'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/learn/$topic'
    | '/levels/$level'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/categories'
    | '/credits'
    | '/daily'
    | '/faq'
    | '/favorites'
    | '/glossary'
    | '/maruf'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/learn/$topic'
    | '/levels/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  CategoriesRoute: typeof CategoriesRoute
  CreditsRoute: typeof CreditsRoute
  DailyRoute: typeof DailyRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  GlossaryRoute: typeof GlossaryRoute
  MarufRoute: typeof MarufRoute
  RoadmapRoute: typeof RoadmapRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LearnTopicRoute: typeof LearnTopicRoute
  LevelsLevelRoute: typeof LevelsLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maruf': {
      id: '/maruf'
      path: '/maruf'
      fullPath: '/maruf'
      preLoaderRoute: typeof MarufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$level': {
      id: '/levels/$level'
      path: '/levels/$level'
      fullPath: '/levels/$level'
      preLoaderRoute: typeof LevelsLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$topic': {
      id: '/learn/$topic'
      path: '/learn/$topic'
      fullPath: '/learn/$topic'
      preLoaderRoute: typeof LearnTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  CategoriesRoute: CategoriesRoute,
  CreditsRoute: CreditsRoute,
  DailyRoute: DailyRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  GlossaryRoute: GlossaryRoute,
  MarufRoute: MarufRoute,
  RoadmapRoute: RoadmapRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategorySlugRoute: CategorySlugRoute,
  LearnTopicRoute: LearnTopicRoute,
  LevelsLevelRoute: LevelsLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
